// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mdm/features/downloader/data/datasources/download_task_schema.dart';
import 'package:mdm/features/history/data/datasources/history_entry_schema.dart';
import 'package:mdm/features/settings/data/repositories/app_settings_schema.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsSchemaAdapter());
    registerAdapter(DownloadTaskSchemaAdapter());
    registerAdapter(HistoryEntrySchemaAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsSchemaAdapter());
    registerAdapter(DownloadTaskSchemaAdapter());
    registerAdapter(HistoryEntrySchemaAdapter());
  }
}
